(setq twittering-initial-timeline-spec-string
      '(":home"
        ":direct_messages"
        "krono/admin"
        "krono/devs"
        "krono/fictional"
        "krono/friends"
        "krono/fun"
        "krono/games"
        "krono/hack"
        "krono/hpi"
        "krono/lp"
        "krono/music"
        "krono/persoenlich"
        "krono/phd"
        "krono/public-interest"
        "krono/py"
        "krono/pypy"
        "krono/research"
        "krono/ruby"
        "krono/self"
        "krono/serious-fun-philosophical"
        "krono/smalltalk"
        "krono/smalltalk-people"
        "krono/smalltalkers"
        "krono/software"
        "krono/tips-misc"
        "krono/typoadmin"
        "krono/devs"
        "krono/fictional"
        "krono/friends"
        "krono/fun"
        "krono/games"
        "krono/hack"
        "krono/hpi"
        "krono/lp"
        "krono/music"
        "krono/persoenlich"
        "krono/phd"
        "krono/public-interest"
        "krono/py"
        "krono/pypy"
        "krono/research"
        "krono/ruby"
        "krono/self"
        "krono/serious-fun-philosophical"
        "krono/smalltalk"
        "krono/smalltalk-people"
        "krono/smalltalkers"
        "krono/software"
        "krono/tips-misc"
        "krono/typo"))
(setq twittering-icon-mode t)
(setq twittering-url-show-status nil)
(add-hook 'twittering-new-tweets-hook
          (lambda ()
            (let ((n twittering-new-tweets-count))
              (do-applescript (format
                               "
tell application \"System Events\"
	display notification \"%d new tweet%s\" with title \"%s\" subtitle \"%s\"
end tell"
                               n (if (> n 1) "s" "") "Twittering" "")))))
